name = "nanmu"
author = "muou_(jj)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff2af4525b9ea339eb096d08e240ad09af61e5c7f7b2c566bc6c7bd5984fee38"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
