name = "nanmu"
author = "muou_(jj)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a233dee4128f76f65eb6522df0c51311714b332a02854a2601f086f27610b43e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
