#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 08 12:40:04 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=
