name = "[万用皮肤补丁] CustomSkinLoader_Universal-15.0.1.jar"
filename = "[万用皮肤补丁] CustomSkinLoader_Universal-15.0.1.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/idMHQ4n2/versions/OLaesh5y/CustomSkinLoader_Universal-15.0.1.jar"
hash-format = "sha1"
hash = "ab8dd841cafc3b4ecbf0250d3f5aee8a1fdb506a"
