name = "[天津地铁] Tianjin-Metro-1.1.1+1.20.1.jar"
filename = "[天津地铁] Tianjin-Metro-1.1.1+1.20.1.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/P0Pb6K4u/versions/a0DMyTtB/Tianjin-Metro-1.1.1%2B1.20.1.jar"
hash-format = "sha1"
hash = "4ed9a31874682ac0f9c2e22932157a25ca71f4af"
