name = "[投影] litematica-fabric-1.20.1-0.15.4.jar"
filename = "[投影] litematica-fabric-1.20.1-0.15.4.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/bEpr0Arc/versions/1ZTpW1lr/litematica-fabric-1.20.1-0.15.4.jar"
hash-format = "sha1"
hash = "68bc88228d567ec0c56dd5d308d51c4cb5eab3ff"
