name = "[荏心音乐机] [荏心音乐机]cp-mod-1.1-1.20.1.jar"
filename = "[荏心音乐机] [荏心音乐机]cp-mod-1.1-1.20.1.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/7dH1UA69/versions/4ATuRQNu/%5B%E8%8D%8F%E5%BF%83%E9%9F%B3%E4%B9%90%E6%9C%BA%5Dcp-mod-1.1-1.20.1.jar"
hash-format = "sha1"
hash = "0bd7c3b789c73e24226432dac516fd75efbc54e1"
