name = "[螃蟹的城建] [螃蟹的城建]crab-city-facilities-1.0.7 1.20-1.20.4.jar"
filename = "[螃蟹的城建] [螃蟹的城建]crab-city-facilities-1.0.7 1.20-1.20.4.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/7ZbCLtRA/versions/Jazbrucm/%5B%E8%9E%83%E8%9F%B9%E7%9A%84%E5%9F%8E%E5%BB%BA%5Dcrab-city-facilities-1.0.7%201.20-1.20.4.jar"
hash-format = "sha1"
hash = "80b0ab7f25bd55b225a3ff179436ffc93e061cd0"
