name = "[螃蟹的路灯] Crab street light 1.20.1_Fabric-1.1.7.jar"
filename = "[螃蟹的路灯] Crab street light 1.20.1_Fabric-1.1.7.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/GouLQh3A/versions/LdcnkQqc/Crab%20street%20light%201.20.1_Fabric-1.1.7.jar"
hash-format = "sha1"
hash = "4bf9016f985ae2bc322ee0cafd22034113d86862"
