name = "Axiom-5.2.1-for-MC1.20.1.jar"
filename = "Axiom-5.2.1-for-MC1.20.1.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/N6n5dqoA/versions/KYfgWqQU/Axiom-5.2.1-for-MC1.20.1.jar"
hash-format = "sha1"
hash = "6b7baa084f10166d7d9924bc6a5b702fc2cc0ca2"
