name = "epicterrain-0.2.5.jar"
filename = "epicterrain-0.2.5.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/7qSJGSHp/versions/R0Bizq64/epicterrain-0.2.5.jar"
hash-format = "sha1"
hash = "267fc898a4954b3084da88205ebef7d2d3f9ac4f"
