name = "jecharacters-1.21.1-fabric-4.5.27.jar"
filename = "jecharacters-1.21.1-fabric-4.5.27.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/I7k4B65h/versions/TFUj4JAg/jecharacters-1.21.1-fabric-4.5.27.jar"
hash-format = "sha1"
hash = "d54e044bee02b87eca3bb9bb1323d49cc33ae7ca"
