name = "sodiumextras-fabric-1.0.7-1.20.1.jar"
filename = "sodiumextras-fabric-1.0.7-1.20.1.jar"
side = "both"
[download]
url = "https://cdn.modrinth.com/data/vqqx0QiE/versions/FdVKLVds/sodiumextras-fabric-1.0.7-1.20.1.jar"
hash-format = "sha1"
hash = "415f6d815b673f6d719c55a7caaa44e03f62bf56"
